name: google_maps_flutter
description: A Flutter plugin for integrating Google Maps in iOS and Android applications.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter
version: 0.5.21+7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # TODO(iskakaushik): The following dependencies can be removed once
  # https://github.com/dart-lang/pub/issues/2101 is resolved.
  flutter_driver:
    sdk: flutter
  test: ^1.6.0

flutter:
  plugin:
    androidPackage: io.flutter.plugins.googlemaps
    iosPrefix: FLT
    pluginClass: GoogleMapsPlugin


environment:
  sdk: ">=2.0.0-dev.47.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
